---
- copy: src=resolv.conf dest=/etc/resolv.conf
- name: install basic packages
  yum: name={{ item }} state=latest
  with_items:
   - epel-release
   - wget
   - unzip
   - net-tools
   - curl
   - libselinux-python
- file: path=/etc/rc.d/rc.local mode=0755
- name: install ntp
  yum: name=ntp state=latest
  notify: restart ntp
- stat: path=/etc/zabbix/zabbix_agentd.conf
  register: zabbix_stat
- name: install zabbix  repo for centos
  yum: name=http://repo.zabbix.com/zabbix/3.2/rhel/{{ ansible_distribution_major_version }}/x86_64/zabbix-release-3.2-1.el{{ ansible_distribution_major_version }}.noarch.rpm state=present
  register: install
  until: install.rc==0  
  retries: 5
  delay: 5
  when: zabbix_stat.stat.exists == False 
- name: install zabbix client
  yum: name=zabbix-agent state=present update_cache=yes
  register: install
  until: install.rc==0
  retries: 5
  delay: 5
  when: zabbix_stat.stat.exists == False
- replace: dest=/etc/zabbix/zabbix_agentd.conf regexp='^(Server|ServerActive)=.*$' replace='\1={{ ZABBIX_SERVER }}' 
  notify: restart zabbix
- name: disable firewall7
  service: name=firewalld state=stopped enabled=no
  when: ansible_distribution_major_version == "7"
- name: disable firewall6
  service: name=iptables state=stopped enabled=no
  when: ansible_distribution_major_version == "6"
- name: disable selinux
  lineinfile: dest=/etc/selinux/config regexp="^SELINUX=.*" line="SELINUX=disabled"
- selinux: state=disabled
- name: set timezone to UTC
  file: src=/usr/share/zoneinfo/UTC dest=/etc/localtime state=link
- name: set hostname
  hostname: name={{hostname}}
  when: hostname is defined
